from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 563)
        MainWindow.setMinimumSize(QtCore.QSize(700, 480))
        MainWindow.setStyleSheet("*{\n"
"background:#18162A;\n"
"border:none;\n"
"color:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.leftMenu = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenu.sizePolicy().hasHeightForWidth())
        self.leftMenu.setSizePolicy(sizePolicy)
        self.leftMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.leftMenu.setStyleSheet("background:#060117; border:none;")
        self.leftMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenu.setLineWidth(0)
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.leftMenu)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dvsoft = QtWidgets.QPushButton(self.frame_4)
        self.dvsoft.setText("DVsoft")
        self.dvsoft.setObjectName("pushButton_9")
        self.dvsoft.setStyleSheet("font-size:32px;")
        self.verticalLayout_3.addWidget(self.dvsoft, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.leftMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Menu2 = QtWidgets.QToolBox(self.frame_5)
        self.Menu2.setStyleSheet("QToolBox{\n"
"    background-color:rgb(24,24,36);\n"
"    text-align:left;\n"
"    font-size:20px;\n"
"    color:white;\n"
"}\n"
"QToolBox::tab{\n"
"    border-radius:5px;\n"
"    background-color:rgb(17,16,26);\n"
"    text-align:left;\n"
"    font-size:20px;\n"
"    color:white;\n"
"}")
        self.Menu2.setObjectName("Menu2")
        self.Menu1 = QtWidgets.QWidget()
        self.Menu1.setGeometry(QtCore.QRect(0, 0, 200, 357))
        self.Menu1.setStyleSheet("")
        self.Menu1.setObjectName("Menu1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Menu1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.Menu1)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        self.pushButton.setStyleSheet("font-size:20px")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_2.setStyleSheet("font-size:20px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_3.setStyleSheet("font-size:20px")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_6.addWidget(self.pushButton_3)
        self.verticalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/strelka3.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu2.addItem(self.Menu1, icon, "")
        self.menu2 = QtWidgets.QWidget()
        self.menu2.setGeometry(QtCore.QRect(0, 0, 200, 357))
        self.menu2.setObjectName("menu2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.menu2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.menu2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_4.setStyleSheet("font-size:20px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_8.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_5.setStyleSheet("font-size:20px")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_8.addWidget(self.pushButton_5)
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setStyleSheet("font-size:20px;")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.Menu2.addItem(self.menu2, icon, "")
        self.verticalLayout_4.addWidget(self.Menu2)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.leftMenu)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.exit = QtWidgets.QPushButton(self.frame_6)
        self.exit.setStyleSheet("font-size:20px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/выход.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon1)
        self.exit.setObjectName("pushButton_12")
        self.horizontalLayout_8.addWidget(self.exit, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.hboxlayout.addWidget(self.leftMenu)
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setStyleSheet("border:none;")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.MainFrame)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setStyleSheet("background:#060117; border:none;")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setLineWidth(0)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuTurn = QtWidgets.QPushButton(self.frame)
        self.menuTurn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/свернуть бар.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuTurn.setIcon(icon2)
        self.menuTurn.setIconSize(QtCore.QSize(32, 32))
        self.menuTurn.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.menuTurn)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setStyleSheet("border-bottom:2px solid #19E67E;\n"
"font-size:24px;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon3)
        self.pushButton_10.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(self.header)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.username = QtWidgets.QPushButton(self.frame_2)
        self.username.setText("USERNAME")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/пользователь.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.username.setIcon(icon4)
        self.username.setIconSize(QtCore.QSize(32, 32))
        self.username.setObjectName("pushButton_9")
        self.username.setStyleSheet("font-size:24px;")
        self.horizontalLayout_4.addWidget(self.username, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.turn = QtWidgets.QPushButton(self.frame_3)
        self.turn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/свернуть.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.turn.setIcon(icon5)
        self.turn.setIconSize(QtCore.QSize(45, 45))
        self.turn.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.turn)
        self.expand = QtWidgets.QPushButton(self.frame_3)
        self.expand.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/двойная диагональная стрелка.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expand.setIcon(icon6)
        self.expand.setIconSize(QtCore.QSize(30, 40))
        self.expand.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.expand)
        self.close = QtWidgets.QPushButton(self.frame_3)
        self.close.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon7)
        self.close.setIconSize(QtCore.QSize(40, 40))
        self.close.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.close)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header)
        self.main = QtWidgets.QFrame(self.MainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.main.setFont(font)
        self.main.setAutoFillBackground(False)
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.main)
        self.label_5.setStyleSheet("border:10px solid #19E67E;\n"
"border-radius:90px;\n"
"padding: 15px")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("icons/логотип.svg"))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.label_6 = QtWidgets.QLabel(self.main)
        self.label_6.setStyleSheet("font-size:50px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.main)
        self.footer = QtWidgets.QFrame(self.MainFrame)
        self.footer.setMinimumSize(QtCore.QSize(50, 50))
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.footer)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setStyleSheet("font-size:14px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.frame_10, 0, QtCore.Qt.AlignLeft)
        self.frame_9 = QtWidgets.QFrame(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.footer)
        self.hboxlayout.addWidget(self.MainFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Menu2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dvsoft.setText(_translate("MainWindow", "DVsoft"))
        self.pushButton.setText(_translate("MainWindow", "Item1"))
        self.pushButton_2.setText(_translate("MainWindow", "Item2"))
        self.pushButton_3.setText(_translate("MainWindow", "Item3"))
        self.Menu2.setItemText(self.Menu2.indexOf(self.Menu1), _translate("MainWindow", "Menu1"))
        self.pushButton_4.setText(_translate("MainWindow", "Weather"))
        self.pushButton_5.setText(_translate("MainWindow", "Course Dollar/Euro"))
        self.label_2.setText(_translate("MainWindow", "Больше информации вы можете прочеcть на нашем сайте, который ещё не готов :)"))
        self.Menu2.setItemText(self.Menu2.indexOf(self.menu2), _translate("MainWindow", "Menu2"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.lineEdit.setText(_translate("MainWindow", "Search"))
        self.label_6.setText(_translate("MainWindow", "DVsoft"))
        self.label_4.setText(_translate("MainWindow", "DVsoft.project.1"))
import icons_rc
